// Auto-generated by scripts/optimize-images.ts — do not edit.
export type OptimizedImage = {
	width: number;
	height: number;
	widths: number[];
};

export const IMAGE_MANIFEST = {
	"01": {
		"width": 3000,
		"height": 4000,
		"widths": [
			320,
			640,
			960,
			1280,
			1920
		]
	},
	"02": {
		"width": 1280,
		"height": 1600,
		"widths": [
			320,
			640,
			960,
			1280
		]
	},
	"03": {
		"width": 2252,
		"height": 4000,
		"widths": [
			320,
			640,
			960,
			1280,
			1920
		]
	},
	"04": {
		"width": 2252,
		"height": 4000,
		"widths": [
			320,
			640,
			960,
			1280,
			1920
		]
	},
	"05": {
		"width": 2252,
		"height": 4000,
		"widths": [
			320,
			640,
			960,
			1280,
			1920
		]
	},
	"06": {
		"width": 2252,
		"height": 4000,
		"widths": [
			320,
			640,
			960,
			1280,
			1920
		]
	},
	"07": {
		"width": 2252,
		"height": 4000,
		"widths": [
			320,
			640,
			960,
			1280,
			1920
		]
	},
	"08": {
		"width": 2252,
		"height": 4000,
		"widths": [
			320,
			640,
			960,
			1280,
			1920
		]
	},
	"borrel": {
		"width": 3000,
		"height": 4000,
		"widths": [
			320,
			640,
			960,
			1280,
			1920
		]
	},
	"hero": {
		"width": 3000,
		"height": 4000,
		"widths": [
			320,
			640,
			960,
			1280,
			1920
		]
	},
	"toetjes": {
		"width": 3000,
		"height": 4000,
		"widths": [
			320,
			640,
			960,
			1280,
			1920
		]
	}
} as const satisfies Record<string, OptimizedImage>;

export type OptimizedImageName = keyof typeof IMAGE_MANIFEST;
