// Auto-generated by scripts/optimize-images.ts — do not edit.
export type OptimizedImage = {
	width: number;
	height: number;
	widths: number[];
};

export const IMAGE_MANIFEST = {
	"02": {
		"width": 1280,
		"height": 1600,
		"widths": [
			320,
			640,
			960,
			1280
		]
	},
	"burrata_closeup": {
		"width": 5000,
		"height": 3333,
		"widths": [
			320,
			640,
			960,
			1280,
			1920
		]
	},
	"burrata_trio": {
		"width": 2252,
		"height": 4000,
		"widths": [
			320,
			640,
			960,
			1280,
			1920
		]
	},
	"charlotte_2": {
		"width": 2252,
		"height": 4000,
		"widths": [
			320,
			640,
			960,
			1280,
			1920
		]
	},
	"charlotte_3": {
		"width": 2252,
		"height": 4000,
		"widths": [
			320,
			640,
			960,
			1280,
			1920
		]
	},
	"charlotte_evenement": {
		"width": 2500,
		"height": 3333,
		"widths": [
			320,
			640,
			960,
			1280,
			1920
		]
	},
	"charlotte_main": {
		"width": 2252,
		"height": 4000,
		"widths": [
			320,
			640,
			960,
			1280,
			1920
		]
	},
	"gijs_2": {
		"width": 3000,
		"height": 4000,
		"widths": [
			320,
			640,
			960,
			1280,
			1920
		]
	},
	"gijs_3": {
		"width": 3000,
		"height": 4000,
		"widths": [
			320,
			640,
			960,
			1280,
			1920
		]
	},
	"gijs_evenement": {
		"width": 3414,
		"height": 4552,
		"widths": [
			320,
			640,
			960,
			1280,
			1920
		]
	},
	"gijs_main": {
		"width": 3000,
		"height": 4000,
		"widths": [
			320,
			640,
			960,
			1280,
			1920
		]
	},
	"hero": {
		"width": 5000,
		"height": 3333,
		"widths": [
			320,
			640,
			960,
			1280,
			1920
		]
	},
	"HH_burrata_3 (1)": {
		"width": 2252,
		"height": 4000,
		"widths": [
			320,
			640,
			960,
			1280,
			1920
		]
	},
	"HH_burrata_Parma": {
		"width": 2252,
		"height": 4000,
		"widths": [
			320,
			640,
			960,
			1280,
			1920
		]
	},
	"HH_burrata_Peach": {
		"width": 2252,
		"height": 4000,
		"widths": [
			320,
			640,
			960,
			1280,
			1920
		]
	},
	"HH_burrata_T": {
		"width": 2252,
		"height": 4000,
		"widths": [
			320,
			640,
			960,
			1280,
			1920
		]
	},
	"owners": {
		"width": 4100,
		"height": 3333,
		"widths": [
			320,
			640,
			960,
			1280,
			1920
		]
	},
	"WhatsApp Image 2026-04-26 at 17.13.04": {
		"width": 1452,
		"height": 1600,
		"widths": [
			320,
			640,
			960,
			1280
		]
	}
} as const satisfies Record<string, OptimizedImage>;

export type OptimizedImageName = keyof typeof IMAGE_MANIFEST;
