import { readdir, mkdir, stat, writeFile, rm } from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';

const SRC_DIR = path.resolve('static/images');
const OUT_DIR = path.resolve('static/images/optimized');
const MANIFEST_PATH = path.resolve('src/lib/image-manifest.ts');

const WIDTHS = [320, 640, 960, 1280, 1920] as const;
const WEBP_QUALITY = 82;
const AVIF_QUALITY = 55;

type Manifest = Record<
	string,
	{
		width: number;
		height: number;
		widths: number[];
	}
>;

const SOURCE_EXTENSIONS = new Set(['.jpg', '.jpeg', '.png']);

async function listSourceImages(): Promise<string[]> {
	const entries = await readdir(SRC_DIR, { withFileTypes: true });
	return entries
		.filter((e) => e.isFile() && SOURCE_EXTENSIONS.has(path.extname(e.name).toLowerCase()))
		.map((e) => path.join(SRC_DIR, e.name));
}

function formatBytes(bytes: number): string {
	if (bytes < 1024) return `${bytes} B`;
	if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
	return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
}

async function fileSize(p: string): Promise<number> {
	return (await stat(p)).size;
}

async function processImage(srcPath: string, manifest: Manifest) {
	const baseName = path.basename(srcPath, path.extname(srcPath));
	const image = sharp(srcPath, { failOn: 'error' });
	const metadata = await image.metadata();

	if (!metadata.width || !metadata.height) {
		console.warn(`  ! skipping ${baseName}: missing dimensions`);
		return { bytesIn: 0, bytesOut: 0 };
	}

	const srcWidth = metadata.width;
	const widthsToRender = WIDTHS.filter((w) => w <= srcWidth);
	if (widthsToRender.length === 0) {
		widthsToRender.push(srcWidth);
	}

	manifest[baseName] = {
		width: srcWidth,
		height: metadata.height,
		widths: widthsToRender
	};

	const bytesIn = await fileSize(srcPath);
	let bytesOut = 0;

	for (const w of widthsToRender) {
		const resized = image.clone().resize({ width: w, withoutEnlargement: true });

		const webpPath = path.join(OUT_DIR, `${baseName}-${w}.webp`);
		const avifPath = path.join(OUT_DIR, `${baseName}-${w}.avif`);

		await Promise.all([
			resized.clone().webp({ quality: WEBP_QUALITY, effort: 5 }).toFile(webpPath),
			resized.clone().avif({ quality: AVIF_QUALITY, effort: 4 }).toFile(avifPath)
		]);

		bytesOut += (await fileSize(webpPath)) + (await fileSize(avifPath));
	}

	console.log(
		`  ${baseName}: ${formatBytes(bytesIn)} src → ${formatBytes(bytesOut)} for ${
			widthsToRender.length
		} widths (webp+avif)`
	);

	return { bytesIn, bytesOut };
}

async function writeManifest(manifest: Manifest) {
	const sorted = Object.fromEntries(
		Object.entries(manifest).sort(([a], [b]) => a.localeCompare(b))
	);
	const body = `// Auto-generated by scripts/optimize-images.ts — do not edit.
export type OptimizedImage = {
	width: number;
	height: number;
	widths: number[];
};

export const IMAGE_MANIFEST = ${JSON.stringify(sorted, null, '\t')} as const satisfies Record<string, OptimizedImage>;

export type OptimizedImageName = keyof typeof IMAGE_MANIFEST;
`;
	await writeFile(MANIFEST_PATH, body, 'utf8');
}

async function main() {
	await rm(OUT_DIR, { recursive: true, force: true });
	await mkdir(OUT_DIR, { recursive: true });

	const sources = await listSourceImages();
	if (sources.length === 0) {
		console.log('No source images found in', SRC_DIR);
		return;
	}

	console.log(`Optimizing ${sources.length} images → ${path.relative(process.cwd(), OUT_DIR)}`);

	const manifest: Manifest = {};
	let totalIn = 0;
	let totalOut = 0;

	for (const src of sources) {
		const { bytesIn, bytesOut } = await processImage(src, manifest);
		totalIn += bytesIn;
		totalOut += bytesOut;
	}

	await writeManifest(manifest);

	console.log('');
	console.log(`Total source: ${formatBytes(totalIn)}`);
	console.log(`Total renditions (webp+avif, all widths): ${formatBytes(totalOut)}`);
	console.log(`Manifest written to ${path.relative(process.cwd(), MANIFEST_PATH)}`);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
